version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: url-shortener-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
       - ./docker-volumes/postgres:/var/lib/postgresql/data